name: CI Actions

on:
  push:
    paths-ignore:
      - '.gitignore'
      - '*.adoc'
      - '*.md'
      - '*.txt'
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]
    paths-ignore:
      - '.gitignore'
      - '*.adoc'
      - '*.md'
      - '*.txt'

env:
  MAVEN_OPTS: '-e -B -Dformatter.skip -Dimpsort.skip'

jobs:
  setup-jdk-mvn:
    name: Setup JDK & Maven
    runs-on: ubuntu-latest
    if: github.repository == 'cameronprater/emoji-java'
    steps:
      - uses: actions/checkout@v2
      - uses: n1hility/cancel-previous-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup JDK
        uses: joschi/setup-jdk@v2
        with:
          java-version: 8
      - name: Maven Clean Install
        run: mvn -e -B -DskipTests clean install
      - name: Upload Build Artifacts
        shell: bash
        run: tar -czf mvn-repo.tgz -C ~ .m2/repository
        uses: actions/upload-artifact@v2
        with:
          name: mvn-repo
          path: mvn-repo.tgz
      - name: Remove Build Artifacts
        shell: bash
        run: rm -r ~/.m2/repository/com/cameronprater
  run-jvm-tests:
    name: Run JVM Tests
    runs-on: ubuntu-latest
    if: github.repository == 'cameronprater/emoji-java'
    needs: setup-jdk-mvn
    steps:
      - uses: actions/checkout@v2
      - name: Download Build Artifacts
        uses: actions/download-artifact@v2
        with:
          name: mvn-repo
        shell: bash
        run: tar -xzf mvn-repo.tgz -C ~
      - name: Maven Install
        run: mvn install
      - name: Upload Test Reports
        if: failure()
        shell: bash
        run: find . -name '*-reports' -type d | tar -czf test-reports.tgz -T -
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: test-reports.tgz